### PR TITLE
work-arounds for GDAL >= 3 & PROJ >= 6 failures

### PR DESCRIPTION
**Pull request by rsbivand**
The man/ pages, DESCRIPTION, and NAMESPACE have been edited manually, as I do not use or trust **roxygen**. If you re-run **roxygen**, you'll need to pick up the breakages. If you do not need p4s= arguments in the `load_*()`, remove them, but you do need to have checked with **rgdal** built using GDAL >= 3 and PROJ >= 6 first. You also need to run check with rgdal built with older PROJ and GDAL for safety's sake.

### CODE REVIEW

**Comment by mdsumner** [comment]
Thanks Roger, my read of the proj4string problem is that "+datum=WGS84" is appropriate and "+elllps=WGS84" is not. That accords with current sp in terms of warnings, I see with towgs84 the datum is forced to ellps, but without towgs84 we seem compliant. I've been confused by this, but everywhere else I've touched I've simply moved to the simpler "+datum=WGS84" which seems to make things work. 

``` r
tw_e <- "+proj=laea +lat_0=-90 +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"
sp::CRS(tw_e)
#> Warning in showSRID(uprojargs, format = "PROJ", multiline = "NO"): Discarded datum Unknown based on WGS84 ellipsoid in CRS definition,
#>  but +towgs84= values preserved
#> CRS arguments:
#>  +proj=laea +lat_0=-90 +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84
#> +towgs84=0,0,0,0,0,0,0 +units=m +no_defs

tw_d <- "+proj=laea +lat_0=-90 +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"
sp::CRS(tw_d)
#> Warning in showSRID(uprojargs, format = "PROJ", multiline = "NO"): Discarded datum WGS_1984 in CRS definition,
#>  but +towgs84= values preserved
#> CRS arguments:
#>  +proj=laea +lat_0=-90 +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84
#> +towgs84=0,0,0,0,0,0,0 +units=m +no_defs

pe <- "+proj=laea +lat_0=-90 +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +units=m +no_defs"
sp::CRS(pe)
#> Warning in showSRID(uprojargs, format = "PROJ", multiline = "NO"): Discarded
#> datum Unknown based on WGS84 ellipsoid in CRS definition
#> CRS arguments:
#>  +proj=laea +lat_0=-90 +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +units=m
#> +no_defs

pd <- "+proj=laea +lat_0=-90 +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84  +units=m +no_defs"
sp::CRS(pd)
#> CRS arguments:
#>  +proj=laea +lat_0=-90 +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m
#> +no_defs
```

<sup>Created on 2020-06-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


My take is that `"+proj=laea +lat_0=-90 +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84  +units=m +no_defs"` is harmless and appropriate, but am I missing something?

**Comment by sthanassekos** [comment]
I have reached the same conclusion as Mike, see below:

Here’s a piece of code, which I believe points to the issues (get some Lat/Lon data, make a SpatialPointsDataFrame then project to lambert eae):
 
Input=data.frame(Lat=runif(100,min=-65,max=-50),
                  Lon=runif(100,min=20,max=40))
 
We used to do this:
Locs=SpatialPointsDataFrame(cbind(Input[,2],Input[,1]),Input,proj4string=CRS("+proj=longlat +ellps=WGS84"))
Which gives a warning 
 
This does not give a warning:
Locs=SpatialPointsDataFrame(cbind(Input[,2],Input[,1]),Input,proj4string=CRS("+proj=longlat +datum=WGS84 +no_defs"))
 
#With a resulting CRS:
proj4string(Locs)
[1] "+proj=longlat +datum=WGS84 +no_defs"
 
This was our CRS argument:
CCAMLRp="+proj=laea +lat_0=-90 +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0"
 
Locs=spTransform(Locs,CRS(CCAMLRp))
 
The resulting CRS is:
proj4string(Locs)
[1] "+proj=laea +lat_0=-90 +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"
So the datum is gone and the towgs84 has 7 numbers
 
If we use this:
CCAMLRp2="+proj=laea +lat_0=-90 +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs"
Locs=spTransform(Locs,CRS(CCAMLRp2))
We don't get a warning, and:
proj4string(Locs)
[1] "+proj=laea +lat_0=-90 +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs"
 

It seems that the correct CRS args would then be,
for raw Lat/Lon data:
"+proj=longlat +datum=WGS84 +no_defs"
for projected data:
"+proj=laea +lat_0=-90 +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs"

**Comment by sthanassekos** [comment]
Also, please note that forcing the p4s in the load_*() functions might be an independent issue. It was done at the time because Linux-based OS seemed to lose the CRS argument when loading objects via GeoJson. This will probably stay as is until we change the way objects are loaded from our online GIS.

**Comment by rsbivand** [comment]
See also https://twitter.com/RogerBivand/status/1268445837824229376 in reply to @mdsumner

**Comment by sthanassekos** [comment]
Now that I've read this

https://www.r-spatial.org/r/2020/03/17/wkt.html

I wonder, can someone write a WKT file (or an R list) and reuse it? Instead of a crs string.

**Comment by sthanassekos** [comment]
Sorry I'm not on twitter but I saw your question:

At what scale and output resolution  is +ellps enough?

I'd really like to know the answer, since I routinely plot maps spanning about the quarter of the globe.

**Comment by mdsumner** [comment]
I think our position is fine @sthanassekos (with data at this scale) - if I figure out why there's this confusion with ellps vs datum I'll let you know.

sp does (now) store the crs in WKT form in the obscure "comment" mechanism, it's effectively a hidden attribute. 
See

```R
x <- load_ASDs()
writeLines(
comment(x@proj4string)
)

```

EDIT: I don't know it seems so wrong atm, I might have done something weird

**Comment by sthanassekos** [comment]
I've reused your trick using comment() and now I see that the WKT argument is automatically generated - but is it right? This is all confusing.

```
Input=data.frame(Lat=runif(100,min=-65,max=-50),Lon=runif(100,min=20,max=40))
Locs=SpatialPointsDataFrame(cbind(Input[,2],Input[,1]),Input,proj4string=CRS("+proj=longlat +datum=WGS84 +no_defs"))
cat(comment(Locs@proj4string))
# GEOGCRS["unknown",
#         DATUM["World Geodetic System 1984",
#               ELLIPSOID["WGS 84",6378137,298.257223563,
#                         LENGTHUNIT["metre",1]],
#               ID["EPSG",6326]],
#         PRIMEM["Greenwich",0,
#                ANGLEUNIT["degree",0.0174532925199433],
#                ID["EPSG",8901]],
#         CS[ellipsoidal,2],
#         AXIS["longitude",east,
#              ORDER[1],
#              ANGLEUNIT["degree",0.0174532925199433,
#                        ID["EPSG",9122]]],
#         AXIS["latitude",north,
#              ORDER[2],
#              ANGLEUNIT["degree",0.0174532925199433,
#                        ID["EPSG",9122]]]]
CCAMLRp2="+proj=laea +lat_0=-90 +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs"
Locs=spTransform(Locs,CRS(CCAMLRp2))
cat(comment(Locs@proj4string))
# PROJCRS["unknown",
#         BASEGEOGCRS["unknown",
#                     DATUM["World Geodetic System 1984",
#                           ELLIPSOID["WGS 84",6378137,298.257223563,
#                                     LENGTHUNIT["metre",1]],
#                           ID["EPSG",6326]],
#                     PRIMEM["Greenwich",0,
#                            ANGLEUNIT["degree",0.0174532925199433],
#                            ID["EPSG",8901]]],
#         CONVERSION["unknown",
#                    METHOD["Lambert Azimuthal Equal Area",
#                           ID["EPSG",9820]],
#                    PARAMETER["Latitude of natural origin",-90,
#                              ANGLEUNIT["degree",0.0174532925199433],
#                              ID["EPSG",8801]],
#                    PARAMETER["Longitude of natural origin",0,
#                              ANGLEUNIT["degree",0.0174532925199433],
#                              ID["EPSG",8802]],
#                    PARAMETER["False easting",0,
#                              LENGTHUNIT["metre",1],
#                              ID["EPSG",8806]],
#                    PARAMETER["False northing",0,
#                              LENGTHUNIT["metre",1],
#                              ID["EPSG",8807]]],
#         CS[Cartesian,2],
#         AXIS["(E)",north,
#              MERIDIAN[90,
#                       ANGLEUNIT["degree",0.0174532925199433,
#                                 ID["EPSG",9122]]],
#              ORDER[1],
#              LENGTHUNIT["metre",1,
#                         ID["EPSG",9001]]],
#         AXIS["(N)",north,
#              MERIDIAN[0,
#                       ANGLEUNIT["degree",0.0174532925199433,
#                                 ID["EPSG",9122]]],
#              ORDER[2],
#              LENGTHUNIT["metre",1,
#                         ID["EPSG",9001]]]]
```

**Comment by mdsumner** [comment]
Yes, looks fine to me. The WKT is just long-form with all explicit parameters, so it's very hard to read  - there's no "glance" and pick up the key components that's for sure. 

The old proj way was liberal defaults, so if something wasn't specified it was assumed (like +x_0=0, +lon_0=0 and so on, but that causes problems with datums because conversions between those really need full parameter sets and "defaults" have changed over time or in different contexts assumed.

**Comment by mdsumner** [comment]
The only important test a visual one, the map looks right and things line up. When precision matters look more closely ;)

**Comment by sthanassekos** [comment]
@mdsumner Thanks Mike, then I'll go with those CRS arguments to fix the package. @rsbivand if you could confirm this is an acceptable approach to you too, that'd be lovely.

**Comment by rsbivand** [comment]
It sounds sound, but you'd need to run CMD check on your package with old PROJ/GDAL, then with new PROJ/GDAL (say CRAN Windows **rgdal** binaries for 1.4-8 for R 3.5 https://cran.r-project.org/bin/windows/contrib/3.5/rgdal_1.4-8.zip and current 1.5.8 https://cran.r-project.org/bin/windows/contrib/4.0/rgdal_1.5-8.zip on R 4.0). Just to be on the safe side ...

**Comment by sthanassekos** [comment]
I've submitted an update to CRAN.
check() on my windows machine worked fine. Wasn't able to load and test R 3.5 unfortunately (or R 3.6).
check_Rhub had mixed results:
All good on Fedora Linux, R-devel, clang, gfortran
PREPERROR on Ubuntu Linux 16.04 LTS, R-release, GCC (installation of package ‘rgdal’ had non-zero exit status)
ERROR on Windows Server 2008 R2 SP1, R-devel, 32/64 bit (namespace 'vctrs' 0.2.4 is being loaded, but >= 0.3.0 is required; Error: package 'dplyr' could not be loaded)

**Comment by mdsumner** [comment]
Try again in a bit, vctrs just hit cran I see these transient issues now and then. Looks like currently the vctrs rdev binary has to catch up

**Comment by mdsumner** [comment]
Looking at the windows binaries i.e 
https://cran.r-project.org/web/packages/vctrs/index.html

**Comment by sthanassekos** [comment]
Package was updated. Thanks a lot for your advice.

**Comment by rsbivand** [comment]
Confirmed 3.0.4 passing CMD check for development version of **rgdal** 1.5-9 rev. 1000.

**Comment by sthanassekos** [comment]
Thank you Roger.

**Pull request closed without merging**
